netflix/src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmsRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $synopsis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $acteur_principal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getActeurPrincipal(): ?string
    {
        return $this->acteur_principal;
    }

    public function setActeurPrincipal(?string $acteur_principal): self
    {
        $this->acteur_principal = $acteur_principal;

        return $this;
    }
}

netflix/src/Controller/AccueilController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Favoris;
use App\Repository\FavorisRepository;
use App\Repository\FilmRepository;

class AccueilController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function index(FilmRepository $filmRepository, FavorisRepository $favorisRepository, EntityManagerInterface $entityManager): Response
    {
    	$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
		$utilisateurId = $this->getUser()->getId();
		// Si on ajoute un film dans les favoris (en cliquant sur une image parmi les films disponibles)
		if (isset($_GET['ajouterFavori']) && is_numeric($_GET['ajouterFavori']))
		{
			// On crée un nouvel objet Favori
			$favori = new Favoris();
			// On lui attribue l'id Utilisateur qui est celui qui est actuellement connecté
			$favori->setIdUtilisateur($utilisateurId);
			// On lui dit l'id du film que l'utilisateur a cliqué
			$favori->setIdFilm($_GET['ajouterFavori']);
			// On met à jour la base de données
			$entityManager->persist($favori);
            $entityManager->flush();
		}
		// Si on supprime un film des favoris (en cliquant sur une image parmi les films favoris)
		if (isset($_GET['supprimerFavori']) && is_numeric($_GET['supprimerFavori']))
		{
			$favorisRepository->supprimer($_GET['supprimerFavori'],$utilisateurId);
		}
        return $this->render('accueil/index.html.twig', [
			'favoris' => $favorisRepository->getFavoris($utilisateurId),
			'films' => $filmRepository->findAll()
        ]);
    }
}

netflix/templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Netflix - Accueil{% endblock %}

{% block body %}
<div class="accueil_container">
	<h2>Vos films favoris</h2>
	{% if favoris %}
		<div class="liste_films">
			{% for favori in favoris %}
				<div class="carte">
					<img class="affiche" src="films/{{ favori.titre }}" onclick="window.location.href='?supprimerFavori={{ favori.id }}'">
					<div>
						<p>Synopsis :</p>
						<p>{{ favori.synopsis }}</p>
					</div>
					<div>
						<p>Acteurs principaux :</p>
						<p>{{ favori.acteur_principal }}</p>
					</div>
				</div>
			{% endfor %}
		</div>
	{% else %}
		<p>Vous n'avez pas de film favori</p>
	{% endif %}
</div>
<div class="accueil_container">
	<h2>Liste des films disponibles Netflix</h2>
	<div class="liste_films">
		{% for film in films %}
			<div class="carte">
				<img class="affiche" src="films/{{ film.titre }}" onclick="window.location.href='?ajouterFavori={{ film.id }}'">
				<div>
					<p>Synopsis :</p>
					<p>{{ film.synopsis }}</p>
				</div>
				<div>
					<p>Acteurs principaux :</p>
					<p>{{ film.acteurPrincipal }}</p>
				</div>
			</div>
		{% endfor %}
	</div>
</div>
{% endblock %}